vector_db:
    index_name: "trading-bot"

embedding_model:
  provider_name: "openai"
  model_name: "BAAI/bge-large-en-v1.5"

llm:
  provider: "meta"
  model: "llama-3.1-8b-instant"




retriever:
  top_k: 3
  score_threshold: 0.5




tools:
  tavily:
    max_results: 5



